"""Install a double-clickable launcher for the web app.

Mirrors the sibling ``scrollback`` project's ``launcher_install.py``.
``argo-anywhere install-launcher`` drops a persistent launcher a non-terminal
user can double-click:

* macOS  -> ``~/Desktop/argo-anywhere.command``, and optionally a real
            ``~/Applications/argo-anywhere.app`` bundle.
* Linux  -> a ``.desktop`` entry in the application menu + a
            ``~/Desktop/argo-anywhere.sh``.

Each launcher **bakes the absolute interpreter path** -- Finder/GUI launches run
with a minimal PATH that excludes venv/conda bins, so relying on a ``PATH``
lookup of the ``argo-anywhere`` console script would fail. The launcher runs
``python -m argo_anywhere app`` (the native pywebview window, which itself falls
back to the browser if pywebview isn't installed).

It never overwrites without saying so, and it prints exactly what it created --
so there is no hidden state (the same footprint ``argo-anywhere info`` lists and
``argo-anywhere uninstall`` removes).

argo-anywhere targets macOS + Linux (its transport is SSH + Duo to ANL); there is
no Windows launcher.
"""

from __future__ import annotations

import shlex
import stat
import sys
from importlib import resources
from pathlib import Path

_APP_NAME = "argo-anywhere"
_BUNDLE_ID = "io.github.a-attia.argo-anywhere"


def _interpreter() -> str:
    """Absolute path of the Python running us (has argo-anywhere installed)."""
    return sys.executable or "python3"


def _desktop_dir(home: Path) -> Path:
    d = home / "Desktop"
    return d if d.is_dir() else home


def _make_executable(path: Path) -> None:
    mode = path.stat().st_mode
    path.chmod(mode | stat.S_IXUSR | stat.S_IXGRP | stat.S_IXOTH)


def _write(path: Path, content: str, *, executable: bool = False) -> None:
    path.write_text(content, encoding="utf-8")
    if executable:
        _make_executable(path)


# -- generated launcher scripts (interpreter baked in) ---------------------

def _terminal_launch_script() -> str:
    """A launcher that opens a terminal window and starts the app (Desktop
    ``.command`` on macOS / ``.sh`` on Linux)."""
    py = shlex.quote(_interpreter())
    return (
        "#!/bin/bash\n"
        "# Generated by `argo-anywhere install-launcher`. Double-click to run.\n"
        f"PY={py}\n"
        'if [ ! -x "$PY" ]; then PY="$(command -v python3 || command -v python)"; fi\n'
        'echo "Starting argo-anywhere  (close the app window to stop)"\n'
        'exec "$PY" -m argo_anywhere app\n'
    )


def _app_runner_script() -> str:
    """The launcher inside a macOS ``.app`` bundle: no terminal, so log to a
    file for post-mortem of a silent GUI failure."""
    py = shlex.quote(_interpreter())
    return (
        "#!/bin/bash\n"
        "# Generated by `argo-anywhere install-launcher`.\n"
        f"PY={py}\n"
        'LOG="$HOME/Library/Logs/argo-anywhere-launcher.log"\n'
        'mkdir -p "$(dirname "$LOG")" 2>/dev/null\n'
        'if [ ! -x "$PY" ]; then PY="$(command -v python3 || command -v python)"; fi\n'
        'exec "$PY" -m argo_anywhere app >> "$LOG" 2>&1\n'
    )


def _desktop_entry() -> str:
    """A Linux ``.desktop`` application-menu entry (interpreter baked, quoted so
    a path with spaces is still valid per the Desktop Entry spec)."""
    py = _interpreter()
    return (
        "[Desktop Entry]\n"
        "Type=Application\n"
        "Name=argo-anywhere\n"
        "Comment=Run AI coding CLIs against the ANL Argo gateway\n"
        f'Exec="{py}" -m argo_anywhere app\n'
        "Terminal=false\n"
        "Categories=Development;Utility;\n"
    )


# -- platform installers ---------------------------------------------------

def install(
    dest: Path | None = None,
    *,
    desktop: bool = False,
    app_bundle: bool = False,
    system: str | None = None,
    home: Path | None = None,
) -> list[Path]:
    """Install the OS-appropriate launcher(s). Returns the paths created.

    Selectors choose WHICH artifacts to create:

    - ``desktop``    -- the Desktop launcher (macOS ``.command`` / Linux
      ``.desktop`` menu entry + ``.sh``).
    - ``app_bundle`` -- a double-clickable ``.app`` (macOS only; on Linux it
      falls back to the Desktop launcher so the flag never errors).

    If **neither** is requested, both are created (the "give me everything"
    default). ``system`` / ``home`` are injectable for tests.
    """
    system = system if system is not None else sys.platform
    home = home if home is not None else Path.home()

    want_desktop = desktop or not (desktop or app_bundle)
    want_app = app_bundle or not (desktop or app_bundle)

    if system == "darwin":
        return _install_macos(dest, home, desktop=want_desktop, app_bundle=want_app)
    return _install_linux(dest, home)


def _install_macos(
    dest: Path | None, home: Path, *, desktop: bool, app_bundle: bool
) -> list[Path]:
    created: list[Path] = []
    if desktop:
        target_dir = dest or _desktop_dir(home)
        target_dir.mkdir(parents=True, exist_ok=True)
        cmd = target_dir / f"{_APP_NAME}.command"
        _write(cmd, _terminal_launch_script(), executable=True)
        created.append(cmd)
    if app_bundle:
        created.append(_build_macos_app(dest, home))
    return created


def _build_macos_app(dest: Path | None, home: Path) -> Path:
    """Create a minimal double-clickable ``argo-anywhere.app`` bundle."""
    base = dest or (home / "Applications")
    base.mkdir(parents=True, exist_ok=True)
    app = base / f"{_APP_NAME}.app"
    macos = app / "Contents" / "MacOS"
    macos.mkdir(parents=True, exist_ok=True)

    runner = macos / _APP_NAME
    _write(runner, _app_runner_script(), executable=True)

    from . import __version__

    # Optional bundled icon (skipped cleanly if the package ships none).
    icon_line = ""
    try:
        icns = resources.files("argo_anywhere").joinpath("assets/icon.icns").read_bytes()
        res_dir = app / "Contents" / "Resources"
        res_dir.mkdir(parents=True, exist_ok=True)
        (res_dir / f"{_APP_NAME}.icns").write_bytes(icns)
        icon_line = f"  <key>CFBundleIconFile</key><string>{_APP_NAME}</string>\n"
    except (OSError, ModuleNotFoundError, FileNotFoundError):
        pass  # icon is optional; the bundle still launches without it

    (app / "Contents" / "Info.plist").write_text(
        '<?xml version="1.0" encoding="UTF-8"?>\n'
        '<!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" '
        '"http://www.apple.com/DTDs/PropertyList-1.0.dtd">\n'
        '<plist version="1.0"><dict>\n'
        "  <key>CFBundleInfoDictionaryVersion</key><string>6.0</string>\n"
        f"  <key>CFBundleName</key><string>{_APP_NAME}</string>\n"
        f"  <key>CFBundleDisplayName</key><string>{_APP_NAME}</string>\n"
        f"  <key>CFBundleIdentifier</key><string>{_BUNDLE_ID}</string>\n"
        f"  <key>CFBundleVersion</key><string>{__version__}</string>\n"
        f"  <key>CFBundleShortVersionString</key><string>{__version__}</string>\n"
        # Populate the standard macOS "About argo-anywhere" panel.
        f"  <key>CFBundleGetInfoString</key><string>argo-anywhere {__version__}, "
        "github.com/a-attia/argo-anywhere</string>\n"
        "  <key>NSHumanReadableCopyright</key><string>MIT-licensed. "
        "github.com/a-attia/argo-anywhere</string>\n"
        "  <key>CFBundlePackageType</key><string>APPL</string>\n"
        f"  <key>CFBundleExecutable</key><string>{_APP_NAME}</string>\n"
        + icon_line
        + "  <key>LSUIElement</key><false/>\n"
        "</dict></plist>\n",
        encoding="utf-8",
    )
    return app


def _install_linux(dest: Path | None, home: Path) -> list[Path]:
    created: list[Path] = []
    # 1) application-menu entry
    apps_dir = dest if dest else home / ".local" / "share" / "applications"
    apps_dir.mkdir(parents=True, exist_ok=True)
    entry = apps_dir / f"{_APP_NAME}.desktop"
    _write(entry, _desktop_entry(), executable=True)
    created.append(entry)
    # 2) a double-clickable copy on the Desktop
    sh = _desktop_dir(home) / f"{_APP_NAME}.sh"
    _write(sh, _terminal_launch_script(), executable=True)
    created.append(sh)
    return created


# -- uninstall / footprint support ----------------------------------------

def installed_artifacts(
    home: Path | None = None, system: str | None = None
) -> list[Path]:
    """Launcher/app/log paths ``install`` may have created, at their DEFAULT
    locations (a custom ``--dest`` is not tracked). Only existing paths.

    Consumed by :mod:`argo_anywhere.footprint` (visibility) and the package
    ``uninstall`` (removal). Never includes the user's agent data.
    """
    home = home if home is not None else Path.home()
    system = system if system is not None else sys.platform

    candidates: list[Path]
    if system == "darwin":
        candidates = [
            _desktop_dir(home) / f"{_APP_NAME}.command",
            home / "Applications" / f"{_APP_NAME}.app",
            home / "Library" / "Logs" / f"{_APP_NAME}-launcher.log",
        ]
    else:
        candidates = [
            home / ".local" / "share" / "applications" / f"{_APP_NAME}.desktop",
            _desktop_dir(home) / f"{_APP_NAME}.sh",
        ]
    return [p for p in candidates if p.exists()]


def remove_path(path: Path) -> None:
    """Delete a file or directory (the ``.app`` bundle is a dir)."""
    import shutil

    if path.is_dir() and not path.is_symlink():
        shutil.rmtree(path)
    else:
        path.unlink()
